root: .
extends: theme-check:recommended
ignore:
  - node_modules/**
AssetPreload:
  enabled: true
  severity: error
BlockIdUsage:
  enabled: true
  severity: error
CdnPreconnect:
  enabled: true
  severity: warning
ContentForHeaderModification:
  enabled: true
  severity: warning
DeprecateBgsizes:
  enabled: true
  severity: error
DeprecateLazysizes:
  enabled: true
  severity: error
DeprecatedFilter:
  enabled: true
  severity: error
DeprecatedFontsOnSectionsAndBlocks:
  enabled: true
  severity: error
DeprecatedFontsOnSettingsSchema:
  enabled: true
  severity: error
DeprecatedTag:
  enabled: true
  severity: error
DuplicateContentForArguments:
  enabled: true
  severity: error
DuplicateRenderSnippetArguments:
  enabled: true
  severity: error
EmptyBlockContent:
  enabled: true
  severity: error
HardcodedRoutes:
  enabled: true
  severity: error
ImgWidthAndHeight:
  enabled: true
  severity: warning
JSONMissingBlock:
  enabled: true
  severity: warning
JSONSyntaxError:
  enabled: true
  severity: warning
LiquidFreeSettings:
  enabled: true
  severity: error
LiquidHTMLSyntaxError:
  enabled: true
  severity: warning
MatchingTranslations:
  enabled: true
  severity: warning
MissingAsset:
  enabled: true
  severity: warning
MissingContentForArguments:
  enabled: true
  severity: error
MissingRenderSnippetArguments:
  enabled: true
  severity: error
MissingTemplate:
  enabled: true
  severity: warning
  ignoreMissing: []
OrphanedSnippet:
  enabled: true
  severity: error
PaginationSize:
  enabled: true
  severity: error
  minSize: 1
  maxSize: 250
ParserBlockingScript:
  enabled: true
  severity: warning
RemoteAsset:
  enabled: true
  severity: error
RequiredLayoutThemeObject:
  enabled: true
  severity: warning
ReservedDocParamNames:
  enabled: true
  severity: warning
SchemaPresetsBlockOrder:
  enabled: true
  severity: error
SchemaPresetsStaticBlocks:
  enabled: true
  severity: warning
StaticStylesheetAndJavascriptTags:
  enabled: true
  severity: warning
TranslationKeyExists:
  enabled: true
  severity: warning
UnclosedHTMLElement:
  enabled: true
  severity: error
UndefinedObject:
  enabled: true
  severity: error
UniqueDocParamNames:
  enabled: true
  severity: warning
UniqueSettingId:
  enabled: true
  severity: warning
UniqueStaticBlockId:
  enabled: true
  severity: warning
UnknownFilter:
  enabled: true
  severity: warning
UnrecognizedContentForArguments:
  enabled: true
  severity: error
UnrecognizedRenderSnippetArguments:
  enabled: true
  severity: error
UnsupportedDocTag:
  enabled: true
  severity: warning
UnusedAssign:
  enabled: true
  severity: error
UnusedDocParam:
  enabled: true
  severity: error
ValidBlockTarget:
  enabled: true
  severity: warning
ValidContentForArgumentTypes:
  enabled: true
  severity: error
ValidContentForArguments:
  enabled: true
  severity: warning
ValidDocParamTypes:
  enabled: true
  severity: warning
ValidHTMLTranslation:
  enabled: true
  severity: error
ValidJSON:
  enabled: true
  severity: warning
ValidLocalBlocks:
  enabled: true
  severity: warning
ValidRenderSnippetArgumentTypes:
  enabled: true
  severity: error
ValidSchema:
  enabled: true
  severity: warning
ValidSchemaName:
  enabled: true
  severity: warning
ValidSettingsKey:
  enabled: true
  severity: warning
ValidStaticBlockType:
  enabled: true
  severity: warning
ValidVisibleIf:
  enabled: true
  severity: warning
VariableName:
  enabled: true
  severity: error
  format: snake_case
