name: Shopify Theme Publish

on:
  workflow_call:
    secrets:
      SHOPIFY_STORE:
        required: true
      THEME_ACCESS_PASSWORD:
        required: true
    inputs:
      theme_name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.THEME_ACCESS_PASSWORD }}
      SHOPIFY_FLAG_FORCE: 1
    steps:
      - name: Publish theme
        run: |
          shopify theme publish "$theme_name" --store="${{ secrets.SHOPIFY_STORE }}"
